### ISSUE TITLE
error 404 - Cannot find definition for MODULE PRECISION_PARAMETERS

### ISSUE THREAD

**Issue by ahsadeghi** [firemodels/radcal#10]
Hi, I have a problem with compiling RadCal source codes separately in Visual Studio and Plato. It seems that the compiler does not recognize the modules used in the source code. Any ideas for solving the problem?  

![image](https://user-images.githubusercontent.com/51397945/60503417-65fd4480-9cc8-11e9-9b83-4ebe8e78102c.png)

![image](https://user-images.githubusercontent.com/51397945/60503706-e9b73100-9cc8-11e9-9472-32b2823ae852.png)

**Comment by rmcdermo** [comment]
Thanks, I'll take a look and get back to you.

**Comment by gforney** [comment]
you need to set up your environmente in visual studio so that it knows where your files are.  open up the properties page for your project, then click on the Fortran tab.  you should see an entry titled "Additional Include Directories".  I would define this entery.

Also, update your rad repo.  I just made some corrections to the makefile and build scripts so you oshould now be able to build radcal from the command line
<img width="388" alt="fds_properties" src="https://user-images.githubusercontent.com/12403014/60512225-03914d80-9ca2-11e9-8d63-c5f74cece5b6.png">

**Comment by ahsadeghi** [comment]
Thanks, all the files were added but still errors appear! My file directory is as follows:

![image](https://user-images.githubusercontent.com/51397945/60529895-45e97780-9d00-11e9-9bd1-66b9949ac62a.png)

Do you have any other ideas?

**Comment by rmcdermo** [comment]
The code builds fine on Linux, so the problem is on your VS set up.  You may have to send the project file to Glenn.  Please post it here.  Append .txt to the file so that it will be allowed as an attachment.

**Comment by gforney** [comment]
#ahsadeghi did you modify your property setting for "Additional Include Directories" ?

**Comment by gforney** [comment]
so you added main.f90, rcal.f90 and rmod.f90 to your project and nothing else?.  you can ignore my comment about include directory.  Don't think you need to set the include directdory parameter.

**Comment by rmcdermo** [comment]
Also, is there a reason why you need to compile?  Have you changed the source?  Did you know there is a Windows exe [here](https://github.com/firemodels/radcal/releases)?

**Comment by ahsadeghi** [comment]
> Also, is there a reason why you need to compile? Have you changed the source? Did you know there is a Windows exe [here](https://github.com/firemodels/radcal/releases)?

@rmcdermo 
Yes, I want to change some parts of the code. I know about .exe.

**Comment by ahsadeghi** [comment]
> so you added main.f90, rcal.f90 and rmod.f90 to your project and nothing else?. you can ignore my comment about include directory. Don't think you need to set the include directdory parameter.

Yes. So you think I should exclude the files rcal.f90 and rmod.f90 ?

**Comment by gforney** [comment]
No. Those are the three files you should have listed. You had 4 files
listed in your earlier posting. Have you tried building radcal from the
command line?
